### ISSUE TITLE
Upgrade axios dependency to fix CVE

### ISSUE THREAD

**Issue by mhatvan** [matyunya/svelte-image#100]
There was a CVE discovered in axios < 0.21.1, please upgrade the dependency to fix this issue.

More details: https://github.com/advisories/GHSA-4w2v-q235-vp99

**Comment by benmccann** [comment]
There's a PR for this: https://github.com/matyunya/svelte-image/pull/99

**Comment by mcmxcdev** [comment]
Fixed via https://github.com/matyunya/svelte-image/pull/99
