### ISSUE TITLE
Nothing generated, empty srcset.

### ISSUE THREAD

**Issue by kevmodrome** [matyunya/svelte-image#17]
I'm having some troubles getting this to work properly with Sapper. I followed the steps in the readme and can get it running. However nothing is generated. It simply replaces the <Image> tag with the following:

```html
<div class="svelte-373mer" style="position: relative; width: 100%;">
    <div style="position: relative; overflow: hidden;">
        <div style="width: 100%; padding-bottom: 100%;"></div>
        <img class="placeholder svelte-373mer" src="test.jpg" alt="Me">
        <picture>
            <source type="image/webp" srcset="">
            <source srcset="">
            <img class="main svelte-373mer" alt="Me" srcset="" width="" height="" sizes="(max-width: 1000px) 100vw, 1000px">
        </picture>
    </div>
</div>
```

The expected behaviour (I would think) is that many images would be generated from "test.jpg" but they are not.

**Comment by kevmodrome** [comment]
It seems this issue is already fixed but was not in the latest release. :) I also discovered some issue with getProp but saw that it was fixed as well.

**Comment by i8ramin** [comment]
Why did you close this issue @kevmodrome. I am experiencing the same problem on latest released version (`0.1.5`)

**Comment by kevmodrome** [comment]
Not sure, haven't used this package in a while. It was working for me though, which is why I closed the issue.

**Comment by d4h0** [comment]
I had the same problem.

For people with the same problem who land here via Google:

Make sure you pass the return value of the svelte-image function to svelte.preprocess, not a reference to the function.

Wrong:

```
svelte({
  preprocess: svelteImage
})
```

Right:

```
svelte({
  preprocess: svelteImage()
})
```

See also: https://github.com/matyunya/svelte-image/issues/41
