### ISSUE TITLE
Disable waypoint

### ISSUE THREAD

**Issue by porfirioribeiro** [matyunya/svelte-image#39]
`svelte-waypoint` is amazing to have image's being loaded only as needed, but when i use `svelte-image` on my `hero` image on top of the website, i don't want to wrap it with `Waypoint` because then when i do `sapper export` the html for the image will not be there and it will give a small layout break, because all markup is there but the image.

For now i am using a custom `Image` element without waypoint, but would be nice to have a prop that could be passed in to disable the lazy loading behaviour

**Comment by matyunya** [comment]
Thanks! This should be available as of 0.1.9.
