### ISSUE TITLE
Add installation instructions for Sapper

### ISSUE THREAD

**Issue by d4h0** [matyunya/svelte-image#40]
Hi,

It seems you forgot to update the readme as you mentioned in [this issue](https://github.com/matyunya/svelte-image/issues/21#issuecomment-550689397) (maybe better only close issues if they are really fixed).

If svelte-image is installed as a dependency (instead of a devDependency) I get the following error:

`<Image> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

After I moved svelte-image to devDepencies the problem seems to be fixed.

Why is this even happening?

In the repo that you posted in the issue linked above, you put svelte-image into the normal dependencies:

https://github.com/matyunya/teatralium-smelte/blob/master/package.json

So I don't understand why this is happening.

**Comment by pablo-abc** [comment]
This is common with Sapper when importing external components.
You can see an explanation here: https://github.com/sveltejs/sapper-template#using-external-components

**Comment by d4h0** [comment]
That makes sense. Thanks, @pablo-abc.
