### ISSUE TITLE
Document 'c' prop for passing CSS classes

### ISSUE THREAD

**Issue by d4h0** [matyunya/svelte-image#42]
I was missing a way to style my images and after looking at the source code I found the [undocumented 'c' prop](https://github.com/matyunya/svelte-image/blob/47d66cfa0450cdaa02bd3311ccbef1e76a1809da/src/Image.svelte#L4) that is applied to the [img tag](https://github.com/matyunya/svelte-image/blob/47d66cfa0450cdaa02bd3311ccbef1e76a1809da/src/Image.svelte#L74).

It would be good if this prop was mentioned in the readme.

However, I think it would be better to rename the prop to something more meaningful (maybe className, as React does, or 'classes', 'class2', 'pass-class', etc.)

Besides that: Shouldn't these classes also be applied to the [placeholder image](https://github.com/matyunya/svelte-image/blob/47d66cfa0450cdaa02bd3311ccbef1e76a1809da/src/Image.svelte#L65)?

**Comment by d4h0** [comment]
Yes, it seems the classes should definitely be also applied to the placeholder.

I have added a height and 'object-fit: cover' to my hero image and at the momen, the placeholder has the full height after loading, which results in a "flash" effect (first the placeholder is loaded at full height, and then the non-placeholder image replaces it at the defined height).

**Comment by matyunya** [comment]
I added documentation to Image component props here: https://github.com/matyunya/svelte-image#image-component-props.

I think one might want to put different classes on placeholder and image, so I split those two in `placeholderClass` and just `class` for now. Let's consider `c` deprecated.

**Comment by d4h0** [comment]
Thanks, @matyunya 

Can you tell me an example in which someone would define different classes for the main and placeholder images? I can't come up with a reason to do this.

Maybe it would be better to use the value of 'class' for both images if 'placeholderClass' is not set.

At the moment, for example, I have to do the following:

```
     <Image
       class="relative hero-height object-cover shadow-md"
       placeholderClass="relative hero-height object-cover shadow-md"
       src="images/mohamed-nohassi-odxB5oIG_iA-unsplash.jpg"
     />
```

...and I would prefer not to have to pass 'placeholderClass' with the same value as 'class'.

With my proposal, if someone needs separate classes for the two images, they could just pass  'placeholderClass'. In the even more unlikely case that someone wants to add classes to the main image and none to the placeholder, he or she could pass  'placeholderClass' with an empty string.
