### ISSUE TITLE
Blur doesn't work on Safari

### ISSUE THREAD

**Issue by dcrck** [matyunya/svelte-image#7]
On Safari:
![Screen Shot 2019-08-03 at 3 48 44 PM](https://user-images.githubusercontent.com/4472562/62417504-eead2e80-b640-11e9-9d84-11f0472c7489.png)

What I expected:
![Screen Shot 2019-08-03 at 3 48 57 PM](https://user-images.githubusercontent.com/4472562/62417505-efde5b80-b640-11e9-8ac5-27411e56adcc.png)

**Comment by matyunya** [comment]
Thanks! Will take a look.

**Comment by matyunya** [comment]
Confirmed. Waypoint doesn't fire on Safari.

**Comment by matyunya** [comment]
@dcrck Please see if it works in 0.0.9

**Comment by dcrck** [comment]
Thanks for working on this! It appears the issue isn't fixed.

![Screen Shot 2019-08-04 at 7 48 32 AM](https://user-images.githubusercontent.com/4472562/62425224-43e05300-b6c8-11e9-9c3a-98a4107f000b.png)

Is there anything I can do to help you debug the issue?

**Comment by matyunya** [comment]
You should delete your `static/g/` folder to regenerate images.
https://svelte-image.matyunya.now.sh should work in Safari now.
The problem is not specific for blur trace type. Webp was generated instead on jpeg/png for non-webp source tag.

**Comment by dcrck** [comment]
Works now, thanks!
